//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Authontication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Service
    {
        public int ServicesID { get; set; }
        public string S_Name { get; set; }
        public string descrip { get; set; }
        public string img { get; set; }
    }
}
